import type { CurrencyRates } from "@/lib/types"; import { createClient } from "@/lib/supabase/server";
const SERIES="TP.DK.USD.A-TP.DK.EUR.A"; const memory:{rates?:CurrencyRates}={};
function fmt(d:Date){return `${String(d.getDate()).padStart(2,"0")}-${String(d.getMonth()+1).padStart(2,"0")}-${d.getFullYear()}`}
function num(v:unknown){return typeof v==="number"?v:typeof v==="string"?Number.parseFloat(v.replace(",",".")):NaN}
export async function fetchTcmbRates():Promise<CurrencyRates>{ if(!process.env.TCMB_EVDS_API_KEY) throw new Error("TCMB_EVDS_API_KEY is missing"); const today=new Date(); const start=new Date(); start.setDate(today.getDate()-10); const url=`https://evds2.tcmb.gov.tr/service/evds/series=${SERIES}&startDate=${fmt(start)}&endDate=${fmt(today)}&type=json&aggregationTypes=last&formulas=0-0&frequency=1`; const res=await fetch(url,{headers:{key:process.env.TCMB_EVDS_API_KEY},cache:"no-store"}); if(!res.ok) throw new Error(`TCMB EVDS failed: ${res.status}`); const data=await res.json(); const last=[...(data.items??[])].reverse().find((r:any)=>num(r?.TP_DK_USD_A)&&num(r?.TP_DK_EUR_A)); const usd=num(last?.TP_DK_USD_A), eur=num(last?.TP_DK_EUR_A); if(!usd||!eur) throw new Error("TCMB invalid payload"); return {USD_TRY:usd,EUR_TRY:eur,fetchedAt:new Date().toISOString(),source:"TCMB-EVDS",stale:false}; }
export async function fetchTcmbTodayXmlFallback():Promise<CurrencyRates>{ const res=await fetch("https://www.tcmb.gov.tr/kurlar/today.xml",{cache:"no-store"}); if(!res.ok) throw new Error(`today.xml failed: ${res.status}`); const xml=await res.text(); const usd=num(xml.match(/Kod="USD"[\s\S]*?<ForexBuying>([\d.]+)<\/ForexBuying>/)?.[1]); const eur=num(xml.match(/Kod="EUR"[\s\S]*?<ForexBuying>([\d.]+)<\/ForexBuying>/)?.[1]); if(!usd||!eur) throw new Error("today.xml invalid"); return {USD_TRY:usd,EUR_TRY:eur,fetchedAt:new Date().toISOString(),source:"TCMB-today.xml",stale:false}; }
async function readCache(){ const supa=createClient(); if(!supa) return null; const {data}=await supa.from("exchange_rates").select("currency_pair,rate,source,fetched_at").order("fetched_at",{ascending:false}).limit(10); const usd=data?.find((r:any)=>r.currency_pair==="USD_TRY"), eur=data?.find((r:any)=>r.currency_pair==="EUR_TRY"); if(!usd||!eur) return null; return {USD_TRY:Number(usd.rate),EUR_TRY:Number(eur.rate),fetchedAt:String(usd.fetched_at),source:String(usd.source??"Supabase-cache"),stale:Date.now()-new Date(String(usd.fetched_at)).getTime()>3600_000}; }
async function writeCache(r:CurrencyRates){ const supa=createClient(); if(supa) await supa.from("exchange_rates").insert([{currency_pair:"USD_TRY",rate:r.USD_TRY,source:r.source},{currency_pair:"EUR_TRY",rate:r.EUR_TRY,source:r.source}]); }
export async function getRatesWithCache():Promise<CurrencyRates>{ if(memory.rates && Date.now()-new Date(memory.rates.fetchedAt).getTime()<3600_000) return memory.rates; const cached=await readCache(); if(cached&&!cached.stale){memory.rates=cached; return cached;} try{const fresh=await fetchTcmbRates(); memory.rates=fresh; await writeCache(fresh); return fresh;}catch(e){try{const fb=await fetchTcmbTodayXmlFallback(); memory.rates=fb; await writeCache(fb); return fb;}catch(x){if(cached) return {...cached,stale:true}; if(memory.rates) return {...memory.rates,stale:true}; throw new Error(`All TCMB sources failed: ${e instanceof Error?e.message:"EVDS"}; ${x instanceof Error?x.message:"XML"}`);}} }
