/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SellRouteImport } from './routes/sell'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ApiStatusRouteImport } from './routes/api-status'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ListingIdRouteImport } from './routes/listing.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatusRoute = ApiStatusRouteImport.update({
  id: '/api-status',
  path: '/api-status',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingIdRoute = ListingIdRouteImport.update({
  id: '/listing/$id',
  path: '/listing/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api-status': typeof ApiStatusRoute
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/methodology': typeof MethodologyRoute
  '/profile': typeof ProfileRoute
  '/sell': typeof SellRoute
  '/signup': typeof SignupRoute
  '/listing/$id': typeof ListingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api-status': typeof ApiStatusRoute
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/methodology': typeof MethodologyRoute
  '/profile': typeof ProfileRoute
  '/sell': typeof SellRoute
  '/signup': typeof SignupRoute
  '/listing/$id': typeof ListingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api-status': typeof ApiStatusRoute
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/methodology': typeof MethodologyRoute
  '/profile': typeof ProfileRoute
  '/sell': typeof SellRoute
  '/signup': typeof SignupRoute
  '/listing/$id': typeof ListingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/api-status'
    | '/auth'
    | '/login'
    | '/marketplace'
    | '/methodology'
    | '/profile'
    | '/sell'
    | '/signup'
    | '/listing/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/api-status'
    | '/auth'
    | '/login'
    | '/marketplace'
    | '/methodology'
    | '/profile'
    | '/sell'
    | '/signup'
    | '/listing/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/api-status'
    | '/auth'
    | '/login'
    | '/marketplace'
    | '/methodology'
    | '/profile'
    | '/sell'
    | '/signup'
    | '/listing/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ApiStatusRoute: typeof ApiStatusRoute
  AuthRoute: typeof AuthRoute
  LoginRoute: typeof LoginRoute
  MarketplaceRoute: typeof MarketplaceRoute
  MethodologyRoute: typeof MethodologyRoute
  ProfileRoute: typeof ProfileRoute
  SellRoute: typeof SellRoute
  SignupRoute: typeof SignupRoute
  ListingIdRoute: typeof ListingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-status': {
      id: '/api-status'
      path: '/api-status'
      fullPath: '/api-status'
      preLoaderRoute: typeof ApiStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listing/$id': {
      id: '/listing/$id'
      path: '/listing/$id'
      fullPath: '/listing/$id'
      preLoaderRoute: typeof ListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ApiStatusRoute: ApiStatusRoute,
  AuthRoute: AuthRoute,
  LoginRoute: LoginRoute,
  MarketplaceRoute: MarketplaceRoute,
  MethodologyRoute: MethodologyRoute,
  ProfileRoute: ProfileRoute,
  SellRoute: SellRoute,
  SignupRoute: SignupRoute,
  ListingIdRoute: ListingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
